# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

jobs:
  lint:
    runs-on: ubuntu-latest

    name: stylelint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run stylelint
